name: financially
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.3
  cloud_firestore: ^4.3.0
  firebase_storage: ^11.0.9
  firebase_analytics: ^10.0.8
  pinput: ^2.2.20
  algolia_helper_flutter: ^0.2.3
  infinite_scroll_pagination: ^3.2.0
  auto_route: ^5.0.4
  fl_chart: ^0.55.2
  url_launcher: ^6.1.7
  uni_links: ^0.5.1
  fluttertoast: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/


